### ISSUE TITLE
thanks, work nown, new assert problem

### ISSUE THREAD

**Issue by gcclua** [jgressmann/pokemon#2] opened 2015-09-26 16:42 UTC
DebuggerState::Mnemonize()
...
            assert(!lua_rawequal(L, index, handleTableIndex)); //@@@@@ here assert fail
            assert(!lua_rawequal(L, index, refTableIndex));
...

my lua function is

function _LoginPacket_create()
    local o = {};
--LoginPacket.__index = LoginPacket;
--setmetatable(o, LoginPacket);
return o;
end

**Comment by jgressmann** [comment] 2015-09-27 20:44
I cannot reproduce the issue with the Lua code you provided. 

I called your function like this

function _LoginPacket_create()
local o = {};
--LoginPacket.__index = LoginPacket;
--setmetatable(o, LoginPacket);
return o;
end

while true do
   _LoginPacket_create()
end

What Lua version did you use?

Cheers,
Jean

**Comment by gcclua** [comment] 2015-09-29 08:13
Hi Cheers, 
        lua's version is 5.1.4 , I has fixed something, main update is add  luaL_loadbuffer() support

        thanks 
        kiler         
  
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
pokemon.cpp

bool
GetLocation(lua_State* L, const lua_Debug& dbg, BufferPtr& filePathBuffer, const char*& filePath, int& line) {
    const int before = lua_gettop(L);
    bool result = true;
    line = dbg.currentline;
    filePath = "";
//##kiler: fixed for path error that use luaL_loadbuffer()
#if 1      
    char c0 = dbg.source[0];
    if (c0 == '@') 
    {
        filePath = dbg.source + 1;
    }
    else if(c0 >= 'a' && c0 <='z')
    {
        filePath = dbg.source;
    }
    else if(c0 >='A' && c0 <='Z')
    {
        filePath = dbg.source;
    }
    else
    {
        result = false;
    }
    
    //if(result == true)
    //{
    //    assert(strstr(dbg.source,".lua")>0);
    //}
#else
    if (dbg.source[0] == '@') {
        filePath = dbg.source + 1;
    } else {
        GetPokemonTable(L, Pokemon_Locations);
        int pops = 1;
        lua_rawgeti(L, -1, 1);
        ++pops;
        const int entries = (int)lua_tointeger(L, -1);
        if (entries) { // possible no one pushed a location
            lua_rawgeti(L, -2, entries + 1);
            ++pops;
            size_t len;
            const char* location = lua_tolstring(L, -1, &len);
            const char* colon = strchr(location, ':');
            assert(colon);
            const size_t filePathLen = len - (colon - location) - 1;
            filePathBuffer.reset(buf_alloc(filePathLen + 1));
            if (filePathBuffer.get()) {
                memcpy(filePathBuffer->beg, colon + 1, filePathLen);
                filePathBuffer->beg[filePathLen] = 0;
                filePath = (char*)filePathBuffer->beg;
                if (line <= 0) {
                    line = 1;
                }
                line += strtol(location, NULL, 10);
            } else {
                result = false;
            }
        } else {
            result = false;
        }
        lua_pop(L, pops);
    }
#endif
    if (result) {
        if (!is_absolute_file_path(filePath)) {
            buffer* buf = NULL;
            result = to_absolute_file_path(&filePath, &buf);
            if (result) {
                assert(buf);
                filePathBuffer.reset(buf);
            }
        }
    }

    const int after = lua_gettop(L);
    assert(before == after);
    POKEMON_UNUSED(before);
    POKEMON_UNUSED(after);

    return result;
}

**Comment by gcclua** [comment] 2015-09-29 13:21
Hi, Cheers

```
      lua's version is 5.1.4, I can always reproduce like follow:
```

in lua files, press step in
                   theCppFunction() -- call Cpp function  

```
      thanks
      Kiler
```

**Comment by jgressmann** [comment] 2015-09-29 13:46
Hi Kiler,

I pushed a change to let you set a callback when a location needs resolving i.e. in essence a custom GetLocation function. I changed example.cpp to use luaL_loadbuffer to demonstrate how it's used.

The example Lua code calls into a C function (sleep) which is registered. If I place a breakpoint on example.lua line 40 and then step into sleep everything works fine.

Cheers,
Jean

**Comment by gcclua** [comment] 2015-09-29 15:24
ok, Thanks, I will check my Cpp inteface source

**Closed as completed** 2015-10-15 17:40 UTC
